version: '3'

services:
  drone:
    image: drone/drone:1
    volumes:
      - /root/.docker/config.json:/root/.docker/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=
      - DRONE_GITHUB_CLIENT_SECRET=
      - DRONE_SERVER_HOST=ci-server.matters.one
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=correct-horse-batter-staple
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_TLS_AUTOCERT=true
    ports:
      - "80:80"
      - "443:443"
    restart: always
