- hosts: all
  vars:
    base_dir: "/home/ubuntu/elasticsearch"
  tasks:
  # - name: Install python 2
  #   become: yes
  #   become_user: root
  #   raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

  - name: Make sure 'ubuntu' group does exist
    group:
      name: ubuntu
      state: present

  - name: Allow 'ubuntu' group to have passwordless sudo
    become: yes
    become_user: root
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%ubuntu'
      line: '%ubuntu ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers to ubuntu group
    become: yes
    become_user: root
    user: name=ubuntu groups=ubuntu append=yes state=present createhome=yes
    
  - name: Add Docker GPG key
    become: yes
    become_user: root
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    become: yes
    become_user: root
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    become: yes
    become_user: root
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'docker-compose']
      state: present
      update_cache: yes
  
  - name: Add ubuntu to docker group
    become: yes
    become_user: root
    user:
      name: '{{ item }}'
      groups: 'docker'
      append: true
    with_items:
      - ubuntu
  
  - name: Update vm.max_map_count to 262144
    become: yes
    become_user: root
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
  
  - name: Copy files to the machines
    become: yes
    become_user: ubuntu
    synchronize: 
      src: '{{ playbook_dir }}/'
      dest: '{{ base_dir }}'
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=.travis.yml"
        - "--exclude=.vagrant"
        - "--exclude=docker/.vagrant"

  - name: Change file ownership
    become: yes
    become_user: root
    file:
      path: '{{ base_dir }}'
      state: directory
      recurse: yes
      owner: ubuntu
      group: ubuntu
