# -*- mode: ruby -*-
# vi: set ft=ruby :

# --- Configuration variables ---
GUI = false
RAM = 6144

# Network configuration
DOMAIN = ".es.matters.news"
NETWORK = "192.168.50."
NETMASK = "255.255.255.0"

BOX = 'ubuntu/bionic64'

HOSTS = {
    "master" => [NETWORK+"10", BOX],
    "worker" => [NETWORK+"11", BOX],
}

# ---- Vagrant configuration -----

Vagrant.require_version ">= 1.7.4"

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = GUI
    vb.memory = RAM
  end

  HOSTS.each do | (name, cfg) |
    ipaddr, box = cfg

    config.vm.define name do |machine|
      machine.vm.box = box
      machine.vm.hostname = name + DOMAIN
      machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK
    end
  end

end
