- hosts: all
  vars:
    base_dir: "/home/ubuntu/ipfs"
  tasks:

  - name: Add Docker GPG key
    become: yes
    become_user: root
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    become: yes
    become_user: root
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    become: yes
    become_user: root
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'docker-compose', 'python3', 'python3-pip']
      state: present
      update_cache: yes
  
  - name: Add ubuntu to docker group
    become: yes
    become_user: root
    user:
      name: '{{ item }}'
      groups: 'docker'
      append: true
    with_items:
      - ubuntu
  
  - name: Copy files to the machines
    synchronize: 
      src: '{{ playbook_dir }}/'
      dest: '{{ base_dir }}'
      rsync_opts:
        - '--exclude=.git'
        - '--exclude=.travis.yml'
        - '--exclude=.vagrant'
        - '--exclude=docker/.vagrant'
        - '--exclude=venv'
        - '--exclude=logs'

- hosts: masters
  vars:
    base_dir: "/home/ubuntu/ipfs"
  tasks:
  - name: Create a cron job to synchronize ipfs cluster
    cron:
      name: 'sync ipfs'
      minute: '0'
      job: 'cd {{ base_dir }} && python3 sync_ipfs_cluster.py > /tmp/cron.log 2>&1'
